### ISSUE TITLE
System.MissingMethodException: Method 'Array.Empty' not found

### ISSUE THREAD

**Issue by Miiite** [azchohfi/Crashlytics.Droid#1]
Hi,

I added the SDK to my app, and did all the necessary steps for creating the app on Fabric's website etc ...
But at runtime when I call IO.Fabric.Sdk.Android.Fabric.With(this, new Com.Crashlytics.Android.Crashlytics()), I get the following exception :

System.MissingMethodException: Method 'Array.Empty' not found. Whould you know anything about that ?

**Comment by azchohfi** [comment]
I'm not aware of this. Maybe it's a new version with some new API that's not mapped correctly... Do you have any more information to help me to track this down?

**Comment by Miiite** [comment]
Sure!
What kind of information do you need to help you track that?

**Comment by chanti-github** [comment]
Hi,
I am also facing same problem. any updates ??

**Comment by azchohfi** [comment]
I'll track  this down ASAP. Thanks for letting me know. I'll try to update to the latest version

**Comment by azchohfi** [comment]
I've found a Xamarin bug to link with this...
https://bugzilla.xamarin.com/show_bug.cgi?id=29882
The fix was quite simple("changed the target version in the Bindings library from use latest to a specific API level"). So I added this:
<TargetFrameworkVersion>v6.0</TargetFrameworkVersion>
I've also updated the binding to use the latest version.
It should work now!
Please verify, so I can close this Issue.

**Comment by chanti-github** [comment]
Hi,
I am Using "Crashlytics Droid" Package from Nuget gallery in this package i am still getting the same error.  Any Updates ??

**Comment by azchohfi** [comment]
Chanti, can you try from the source? The NuGet package is not mine, so it's not using the latest's version. This reminded me that I don't have a NuGet package, which is ridiculous... I'll try to integrate this with the build system ASAP. Thanks for reminding me.

**Comment by naveen003** [comment]
Ok Thanks. Any Plans to create Nuget Pacakage ?? 

Please let me know.

**Comment by azchohfi** [comment]
https://www.nuget.org/packages/Crashlytics.Droid.Binding/

**Comment by Miiite** [comment]
Thanks Alexandre.
The nuget package was actually created by me to fill the gap.

I'll remove the other one from nuget, to let you handle future version
releases and avoid confusion ;)

2016-03-31 9:15 GMT+02:00 Alexandre Zollinger Chohfi <
notifications@github.com>:

**Comment by azchohfi** [comment]
Great, thanks for that btw! That way we at least ensure it will have the most updated version. I've added a build system on VSTS and automated the upload provess to NuGet.org.

**Comment by Miiite** [comment]
I just deactivated my nuget package. So it should be disappear from
nuget.org any minute now ;)

Thanks for the bugfix

2016-03-31 15:26 GMT+02:00 Alexandre Zollinger Chohfi <
notifications@github.com>:

**Comment by azchohfi** [comment]
Great. Just one question remains... Update path for the ~50 users that downloaded it... Is is possible to add a new version that just removes everything and have a dependency to my package? I'm not sure how to proceed, or even if we should.

**Comment by Miiite** [comment]
Well in the description of the nuget package there is the link to your
github.

I think we should just let the 50 users deal with it

2016-03-31 16:25 GMT+02:00 Alexandre Zollinger Chohfi <
notifications@github.com>:

**Comment by azchohfi** [comment]
Ok, not a big problem.
